### ISSUE TITLE
Return key is ignored in chapter "Training and Prediction"

### ISSUE THREAD

**Issue by NicolasAG** [allenai/allennlp-guide#127]
Thank you for making this guide, so far it is really helpful to familiarize myself with the library.

I'm going through the guide and there seems to be a bug in the chapter "**Training and Prediction**" > section 1 "**Training the model with your own script**" > paragraph "**Feeding instances to the model**".
when I try to run the code I get the following return message:

> Encountered the loss key in the model's return dictionary which couldn't be split by the batch size. Key will be ignored.

However, the documentation says:
> When you run this, you should see the outputs returned from the model. Each returned dict includes the loss key as well as the probs key, which contains probabilities for each label.

Below is a screenshot of my interface.

![image](https://user-images.githubusercontent.com/6558229/85442687-77390400-b55e-11ea-9f02-de00ebb3a89a.png)

Note that I didn't edit the original code in the code blocks.
Also, isn't weird that this gets printed _before_ the `print("Building the model")` line?

**Comment by matt-gardner** [comment]
Thanks for the report!

You're seeing that message because it's a warning printed by `model.forward_on_instances()`.  The model produces a loss, but it's not separable into instance-specific output, so we punt on including it, but give you a warning about it (once).

I *think* that you're seeing it before the "Building the model" because of something about how binder is showing you the output - warnings must flush before stdout does, so the messages appear out of order.

I just pushed a change that makes it so that the warning won't be printed, because it's just distracting at this point of the quick start.
